version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-16-may-2021/motion-backend/team2:latest
    restart: always
    env_file:
      - ./envs/dev.env
    command: "sh /scripts/dev.sh"
    ports:
      - '8000:8000'
      - '4777:22'
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files


  # no need for nginx and gunicorn for local development environment (see docker-compose.deploy.yml)


volumes:
  postgres:
  media-files:
  static-files:
