version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./envs/prod.env
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-16-may-2021/motion-backend/team2:latest
    env_file:
      - ./envs/prod.env
    command: "sh ../scripts/run.sh"  # notice the different script and env files for development and production
    depends_on:
      - postgres
    volumes:
      - media-files:/media-files
      - static-files:/static-files
      - frontend:/frontend/build

  nginx:
    image: nginx:1.17.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static-files:/static-files
      - media-files:/media-files
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend:/frontend



volumes:
  postgres:
  static-files:
  media-files:
  frontend:

