name: backend

dependencies:
  - python=3.6
  - psycopg2
  - pip=19.2.3
  - pip:
    - django==3.0.3
    - djangorestframework==3.11.0
    - djangorestframework_simplejwt==4.4.0
    - PyJWT==1.7.1
    - flake8==3.9.2
    - markdown==3.2.1
    - django-filter==2.2.0
    - coreapi==2.3.3
    - Pygments==2.5.2
    - gunicorn==20.1.0
    - Pillow==8.2.0
    - pywebcopy==6.3.0
    - beautifulsoup4==4.7.1
    - django-cors-headers==3.7.0
    - webpreview==1.6.0
    - django-extensions==2.2.5
    - django-fullurl==1.0

